# Generated by Django 5.2.4 on 2025-07-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
